### ISSUE TITLE
[bug] Not Working CustomiuiZer features 

### ISSUE THREAD

**Issue by AraafRoyall** [Xposed-Modules-Repo/com.sevtinge.cemiuiler#1]
hi. in Andoid 11 . miui 12.5 Customiuizer features not working from this app..

i think you should use [this](https://github.com/Xposed-Modules-Repo/org.strawing.customiuizermod) for Android 11 customiuizer features

**Comment by lingqiqi5211** [comment]
Thank you for your reply. I also considered porting this project when porting the source code of other projects before, but I put it on hold because of the large content. I will consider it when porting later

**Comment by AraafRoyall** [comment]
> Thank you for your reply. I also considered porting this project when porting the source code of other projects before, but I put it on hold because of the large content. I will consider it when porting later

Hi. Please do this for us. I really need these features support.
